/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WLMS_WLMS_HEADER_PB_H_INCLUDED
#define PB_WLMS_WLMS_HEADER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _wlms_PacketType {
    wlms_PacketType_PACKET_TYPE_UNSPECIFIED = 0,
    wlms_PacketType_PACKET_TYPE_IMAGE = 1 /* pixel data follows the header area */
} wlms_PacketType;

typedef enum _wlms_HeaderFlag {
    wlms_HeaderFlag_HEADER_FLAG_NONE = 0,
    wlms_HeaderFlag_HEADER_FLAG_RTC_TIMESTAMP = 1 /* timestamp_ms counts the 32.768 kHz crystal, not the TC1 tick */
} wlms_HeaderFlag;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(4) wlms_BufferHeader_black_ref_t;
typedef PB_BYTES_ARRAY_T(4) wlms_BufferHeader_tx_diag_t;
typedef struct _wlms_BufferHeader {
    /* decode key */
    uint32_t firmware_id; /* FW_VERSION_MAJOR << 8 | FW_VERSION_MINOR */
    wlms_PacketType packet_type;
    uint32_t device_id;
    uint32_t flags; /* HeaderFlag bits */
    /* buffer and frame */
    uint32_t frame_number; /* since boot */
    uint32_t buffer_count; /* since boot */
    uint32_t buffer_in_frame; /* 0..7 */
    uint32_t tx_backlog; /* buffers filled but not yet handed to the transmitter */
    uint32_t buffers_lost; /* send-queue overruns since boot */
    uint32_t timestamp_ms; /* since recording start */
    uint32_t pixel_bytes; /* pixel bytes in this buffer */
    /* device state */
    uint32_t battery_adc; /* 8-bit ADC */
    uint32_t input_adc; /* 8-bit ADC, wireless power input */
    bool has_mcu_temp_centi_c;
    int32_t mcu_temp_centi_c; /* 0.01 degC, absent if the sensor has not reported yet */
    uint32_t sensor_temp_raw; /* PYTHON480 die temperature, reg 97, ~0.75 degC/LSB */
    wlms_BufferHeader_black_ref_t black_ref; /* black reference level of the frame, one byte per phase (pixel index % 4) */
    /* transmit ring diagnostics */
    wlms_BufferHeader_tx_diag_t tx_diag; /* slips, slot out of order, restarts skipped, max waiting */
    uint32_t encode_cycles; /* CPU cycles the previous buffer's header encode took */
} wlms_BufferHeader;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _wlms_PacketType_MIN wlms_PacketType_PACKET_TYPE_UNSPECIFIED
#define _wlms_PacketType_MAX wlms_PacketType_PACKET_TYPE_IMAGE
#define _wlms_PacketType_ARRAYSIZE ((wlms_PacketType)(wlms_PacketType_PACKET_TYPE_IMAGE+1))

#define _wlms_HeaderFlag_MIN wlms_HeaderFlag_HEADER_FLAG_NONE
#define _wlms_HeaderFlag_MAX wlms_HeaderFlag_HEADER_FLAG_RTC_TIMESTAMP
#define _wlms_HeaderFlag_ARRAYSIZE ((wlms_HeaderFlag)(wlms_HeaderFlag_HEADER_FLAG_RTC_TIMESTAMP+1))

#define wlms_BufferHeader_packet_type_ENUMTYPE wlms_PacketType


/* Initializer values for message structs */
#define wlms_BufferHeader_init_default           {0, _wlms_PacketType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, 0, 0, {0, {0}}, {0, {0}}, 0}
#define wlms_BufferHeader_init_zero              {0, _wlms_PacketType_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, 0, 0, {0, {0}}, {0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define wlms_BufferHeader_firmware_id_tag        1
#define wlms_BufferHeader_packet_type_tag        2
#define wlms_BufferHeader_device_id_tag          3
#define wlms_BufferHeader_flags_tag              4
#define wlms_BufferHeader_frame_number_tag       5
#define wlms_BufferHeader_buffer_count_tag       6
#define wlms_BufferHeader_buffer_in_frame_tag    7
#define wlms_BufferHeader_tx_backlog_tag         8
#define wlms_BufferHeader_buffers_lost_tag       9
#define wlms_BufferHeader_timestamp_ms_tag       10
#define wlms_BufferHeader_pixel_bytes_tag        11
#define wlms_BufferHeader_battery_adc_tag        12
#define wlms_BufferHeader_input_adc_tag          13
#define wlms_BufferHeader_mcu_temp_centi_c_tag   14
#define wlms_BufferHeader_sensor_temp_raw_tag    15
#define wlms_BufferHeader_black_ref_tag          16
#define wlms_BufferHeader_tx_diag_tag            17
#define wlms_BufferHeader_encode_cycles_tag      18

/* Struct field encoding specification for nanopb */
#define wlms_BufferHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_id,       1) \
X(a, STATIC,   SINGULAR, UENUM,    packet_type,       2) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         3) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             4) \
X(a, STATIC,   SINGULAR, UINT32,   frame_number,      5) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_count,      6) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_in_frame,   7) \
X(a, STATIC,   SINGULAR, UINT32,   tx_backlog,        8) \
X(a, STATIC,   SINGULAR, UINT32,   buffers_lost,      9) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,     10) \
X(a, STATIC,   SINGULAR, UINT32,   pixel_bytes,      11) \
X(a, STATIC,   SINGULAR, UINT32,   battery_adc,      12) \
X(a, STATIC,   SINGULAR, UINT32,   input_adc,        13) \
X(a, STATIC,   OPTIONAL, SINT32,   mcu_temp_centi_c,  14) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_temp_raw,  15) \
X(a, STATIC,   SINGULAR, BYTES,    black_ref,        16) \
X(a, STATIC,   SINGULAR, BYTES,    tx_diag,          17) \
X(a, STATIC,   SINGULAR, UINT32,   encode_cycles,    18)
#define wlms_BufferHeader_CALLBACK NULL
#define wlms_BufferHeader_DEFAULT NULL

extern const pb_msgdesc_t wlms_BufferHeader_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wlms_BufferHeader_fields &wlms_BufferHeader_msg

/* Maximum encoded size of messages (where known) */
#define WLMS_WLMS_HEADER_PB_H_MAX_SIZE           wlms_BufferHeader_size
#define wlms_BufferHeader_size                   107

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
